name: test_flutter_lso
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^1.0.2
  shared_preferences: ^2.0.6
  lottie: ^1.0.1
  restart_app: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
