version: '3'

services:
  serverlso:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: serverlso
    networks:
      mynetwork:
        ipv4_address: 172.20.0.2
    ports:
      - "5050:5050"

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/16
